version: "3.8"

services:
#  base_ubuntu:
#    platform: linux/amd64
#    build:
#      context: .
#      dockerfile: .dockerfiles/Dockerfile.ubuntu

  fastapi:
    container_name: vass_fastapi
    platform: linux/amd64
    build:
      dockerfile: .dockerfiles/Dockerfile.ubuntu
    expose:
      - "9000"
    ports:
      - "9000:9000"
    extra_hosts:
      - "parenthost:172.17.13.25"
      - "otherhost:172.17.5.115"
    entrypoint:
      - -c
      - chmod 777 /srv/project
      - /srv/project/gunicorn_run.sh
#    command:
#      - bash -c chmod -x /srv/project/gunicorn_run.sh
#      - bash -c /srv/project/gunicorn_run.sh

#      - bash -c "cd /srv/project && /root/.pyenv/versions/deploy_docker/bin/gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:9000 --workers 2"
#      - /root/.pyenv/versions/deploy_docker/bin/gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:9000 --workers 2
#      - gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:9000 --workers 2