version: "3.8"

services:
#  base_ubuntu:
#    platform: linux/amd64
#    build:
#      context: .
#      dockerfile: .dockerfiles/Dockerfile.ubuntu

  fastapi:
    container_name: vass_fastapi
    platform: linux/amd64
    build:
      dockerfile: .dockerfiles/Dockerfile
    expose:
      - "9000"
    ports:
      - 9000:80
    volumes:
      - ./:/app
    extra_hosts:
    - "host.docker.internal:host-gateway"
####
# docker run -d --name ms-sql-server -e "ACCEPT_EULA=Y" -e 'SA_PASSWORD=123aaa!@#' -v data:/var/opt/mssql -p 1433:1433 mcr.microsoft.com/azure-sql-edge:latest
# docker run -d --name ms-sql-server -e "ACCEPT_EULA=Y" -e 'SA_PASSWORD=123aaa!@#' -p 1433:1433 mcr.microsoft.com/azure-sql-edge:latest
###